Stubs - Fixes invalid Syntax -
TLDR: Importing rhino3dm causes mypy type checks to fail and cannot be ran on project

No sure if this is automatically generate, but invalid syntax was causing mypy to fail.

As per [PEP-484](https://www.python.org/dev/peps/pep-0484/#stub-files)
_[...] stub files are syntactically valid Python modules_

I was able to fix it by manually fixing a few syntax errors which are shown in this PR.

The two issues are: 
* Indent errors on functions and class with no body
* List types should be `List[int]` and `List[Curve]`. `int[]` and `Curve[]` are invalid intax


### Before Patching
```
.venv ❯ mypy myproject
.venv/lib/python3.7/site-packages/rhino3dm/__init__.pyi:949: error: invalid syntax
```

### After Patching
Type errors/warnings show as expected
```
.venv ❯ mypy by
contrib/rhino/conversion.py:14: error: Incompatible types in assignment (expression has type "Point3d", variable has type "Point")
contrib/rhino/conversion.py:15: error: Argument 1 to "Sphere" has incompatible type "Point"; expected "Point3d"
contrib/rhino/conversion.py:22: error: Incompatible return value type (got "LineCurve", expected "Line")
contrib/rhino/conversion.py:27: error: "Point3d" has no attribute "X"
```